# Generated by Django 4.2.1 on 2023-10-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('sum_paid', models.IntegerField(verbose_name='Оплаченная сумма')),
                ('code', models.CharField(verbose_name='Код')),
                ('time_created', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание сезона')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Пользовательский ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена тура')),
                ('places', models.IntegerField(verbose_name='Общее количество мест')),
                ('free_places', models.IntegerField(verbose_name='Свободные места')),
                ('is_featured', models.BooleanField()),
                ('date_start', models.DateTimeField(verbose_name='Дата старта')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания')),
                ('time_create', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
                ('season', models.ManyToManyField(to='travel_api.season', verbose_name='Сезон')),
                ('status', models.ManyToManyField(to='travel_api.status', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=255, verbose_name='AWS S3 Фото')),
            ],
        ),
        migrations.CreateModel(
            name='TourDayOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('is_landmark', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ManyToManyField(to='travel_api.tour')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number', models.IntegerField(verbose_name='Номер места')),
                ('name', models.CharField(verbose_name='Имя')),
                ('surname', models.CharField(verbose_name='Фамилия')),
                ('phone', models.CharField(verbose_name='Номер телефона')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('is_primary_contact', models.BooleanField()),
                ('verification_code', models.IntegerField(verbose_name='Код верификации')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travel_api.tour'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название опции')),
                ('time_create', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
                ('tour', models.ManyToManyField(to='travel_api.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_url', models.CharField(max_length=255, verbose_name='Ссылка на AWS')),
                ('is_main', models.BooleanField(verbose_name='Главное фото')),
                ('tour_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_api.tour')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('time_create', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
                ('tour', models.ManyToManyField(to='travel_api.tour', verbose_name='Тур')),
            ],
        ),
    ]
