# Generated by Django 4.2.3 on 2023-10-13 18:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('sum_paid', models.IntegerField(verbose_name='Оплаченная сумма')),
                ('code', models.CharField(verbose_name='Код')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание сезона')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('places', models.IntegerField(verbose_name='Кількість місць (Загальна)')),
                ('free_places', models.IntegerField(verbose_name='Кількість вільних місць')),
                ('is_featured', models.BooleanField(verbose_name='Вибраний?')),
                ('date_start', models.DateField(verbose_name='Дата почтаку')),
                ('date_end', models.DateField(verbose_name='Дата кінця')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='season', to='travel_api.season')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travel_api.status', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255, verbose_name='Название дня')),
                ('description', models.TextField(blank=True, verbose_name='Описание дня (необязательно поле)')),
                ('photo', models.URLField(verbose_name='Ссылка на AWS')),
            ],
        ),
        migrations.CreateModel(
            name='TourDayOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='Минмальная длина - 3 символа', regex='^.{3}$')], verbose_name='Название')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(null=True)),
                ('date_start', models.DateTimeField(blank=True)),
                ('date_end', models.DateTimeField(blank=True)),
                ('is_landmark', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('tour_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=models.UUIDField(), related_name='images', serialize=False, to='travel_api.tour')),
                ('aws_url', models.CharField(max_length=255, verbose_name='Ссылка на AWS')),
                ('is_main', models.BooleanField(verbose_name='Главное фото')),
            ],
        ),
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ManyToManyField(related_name='program', to='travel_api.tour')),
                ('tour_dayss', models.ManyToManyField(to='travel_api.tourday')),
                ('tour_option', models.ManyToManyField(to='travel_api.tourdayoption')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number', models.IntegerField(verbose_name='Номер места')),
                ('name', models.CharField(verbose_name='Имя')),
                ('surname', models.CharField(verbose_name='Фамилия')),
                ('phone', models.CharField(verbose_name='Номер телефона')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('is_primary_contact', models.BooleanField()),
                ('verification_code', models.IntegerField(verbose_name='Код верификации')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='travel_api.tour'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='Минмальная длина - 3 символа', regex='^.{3}$')], verbose_name='Название опции')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_landmark', models.BooleanField(blank=True, default=False, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('icon', models.URLField(max_length=500, null=True)),
                ('tour', models.ManyToManyField(blank=True, related_name='option', to='travel_api.tour')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('icon', models.CharField(max_length=255, null=True)),
                ('tour', models.ManyToManyField(related_name='adoption', to='travel_api.tour', verbose_name='Тур')),
            ],
        ),
    ]
