# Generated by Django 4.2.1 on 2023-10-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourprogram',
            name='tour_day',
            field=models.ManyToManyField(to='travel_api.tourday'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='tour_option',
            field=models.ManyToManyField(to='travel_api.tourdayoption'),
        ),
    ]
