# Generated by Django 4.2.3 on 2023-10-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourprogram',
            old_name='tour_dayss',
            new_name='tour_days',
        ),
    ]
