# Generated by Django 4.2.3 on 2023-10-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travel_api", "0002_tourprogram_tour_day_tourprogram_tour_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="id",
        ),
        migrations.AddField(
            model_name="additionaloption",
            name="icon",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="icon",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="image_url",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="is_landmark",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="additionaloption",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="additionaloption",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="additionaloption",
            name="tour",
            field=models.ManyToManyField(
                related_name="adoption", to="travel_api.tour", verbose_name="Тур"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="tour_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=models.UUIDField(),
                related_name="images",
                serialize=False,
                to="travel_api.tour",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="tour",
            field=models.ManyToManyField(related_name="option", to="travel_api.tour"),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="order",
                to="travel_api.tour",
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="date_end",
            field=models.DateField(verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="date_start",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RemoveField(
            model_name="tour",
            name="season",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="status",
        ),
        migrations.AlterField(
            model_name="tour",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tour",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tourprogram",
            name="tour",
            field=models.ManyToManyField(related_name="program", to="travel_api.tour"),
        ),
        migrations.AddField(
            model_name="tour",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="season",
                to="travel_api.season",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="travel_api.status",
                verbose_name="Статус",
            ),
            preserve_default=False,
        ),
    ]
