# Generated by Django 4.2.3 on 2023-10-13 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0002_rename_tour_dayss_tourprogram_tour_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Минмальная длина - 3 символа', regex='^.{3}$')]),
        ),
        migrations.AddField(
            model_name='image',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='icon',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='Минмальная длина - 3 символа', regex='^.{3}$')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='tour',
            field=models.ManyToManyField(blank=True, related_name='adoption', to='travel_api.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='Минмальная длина - 3 символа', regex='^.{3}$')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='Минмальная длина - 3 символа', regex='^.{3}$')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='free_places',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість вільних місць'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Вибраний?'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='Минмальная длина - 3 символа', regex='^.{3}$')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість місць (Загальна)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ціна'),
        ),
    ]
