# Generated by Django 4.2.3 on 2023-10-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0003_image_name_image_time_create_image_time_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaloption',
            name='icon',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
