# Generated by Django 4.2.3 on 2023-10-14 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0006_alter_tour_date_end_alter_tour_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 16, 42, 1, 912368), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 16, 42, 1, 912368), verbose_name='Дата почтаку'),
        ),
    ]
