# Generated by Django 4.2.3 on 2023-10-15 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0009_alter_additionaloption_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 18, 4, 38, 57931), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 18, 4, 38, 57931), verbose_name='Дата почтаку'),
        ),
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='program', to='travel_api.tour')),
                ('tour_days', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travel_api.tourday')),
                ('tour_option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travel_api.tourdayoption')),
            ],
            options={
                'verbose_name': 'Программа туров',
                'verbose_name_plural': 'Программы туров',
            },
        ),
    ]
