# Generated by Django 4.2.3 on 2023-10-15 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0011_alter_tour_date_end_alter_tour_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 18, 21, 8, 620562), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 18, 21, 8, 620562), verbose_name='Дата почтаку'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='program', to='travel_api.tour'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour_days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travel_api.tourday'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travel_api.tourdayoption'),
        ),
    ]
