# Generated by Django 4.2.3 on 2023-10-16 17:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0012_alter_tour_date_end_alter_tour_date_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaloption',
            options={'verbose_name_plural': 'Додаткові витрати'},
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='icon',
            field=models.URLField(max_length=255, null=True, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 16, 20, 37, 50, 520445), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 16, 20, 37, 50, 520445), verbose_name='Дата почтаку'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='photo',
            field=models.URLField(verbose_name='Фото'),
        ),
    ]
