# Generated by Django 4.2.3 on 2023-10-19 15:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0013_alter_additionaloption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Зображення', 'verbose_name_plural': 'Зображення'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Пасажири замовлення'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name_plural': 'Сезони'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Статуси'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['name'], 'verbose_name_plural': 'Тури'},
        ),
        migrations.AlterModelOptions(
            name='tourday',
            options={'verbose_name_plural': 'Дні турів'},
        ),
        migrations.AlterModelOptions(
            name='tourdayoption',
            options={'verbose_name_plural': 'Опції днів'},
        ),
        migrations.AlterModelOptions(
            name='tourprogram',
            options={'verbose_name': 'Програма турів', 'verbose_name_plural': 'Програми турів'},
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Назва опції'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.IntegerField(verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_paid',
            field=models.IntegerField(verbose_name='Сплачена сума'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='phone',
            field=models.CharField(verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sum',
            field=models.IntegerField(verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='surname',
            field=models.CharField(verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='verification_code',
            field=models.IntegerField(verbose_name='Код верифікації'),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис сезону'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 18, 27, 26, 868833), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 18, 27, 26, 868833), verbose_name='Дата почтаку'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='day',
            field=models.CharField(max_length=255, verbose_name='Назва дня'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис дня (необязательно поле)'),
        ),
        migrations.AlterField(
            model_name='tourdayoption',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Назва'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
