# Generated by Django 4.2.3 on 2023-10-19 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0015_alter_option_options_alter_tour_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tour_image',
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 19, 27, 45, 762011), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 19, 27, 45, 762011), verbose_name='Дата почтаку'),
        ),
        migrations.AddField(
            model_name='image',
            name='tour_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='travel_api.tour'),
        ),
    ]
