# Generated by Django 4.2.3 on 2023-10-20 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0016_remove_image_tour_image_alter_tour_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='is_primary_contact',
            field=models.BooleanField(verbose_name='Контакт для звʼязку'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_api.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='place_number',
            field=models.IntegerField(verbose_name='Номер місця'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='surname',
            field=models.CharField(verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 14, 11, 193577), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 14, 11, 193577), verbose_name='Дата почтаку'),
        ),
    ]
