# Generated by Django 4.2.3 on 2023-10-20 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0017_alter_orderitem_is_primary_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 16, 52, 699967), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 16, 52, 699967), verbose_name='Дата почтаку'),
        ),
    ]
