# Generated by Django 4.2.3 on 2023-10-20 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0018_orderitem_time_create_alter_tour_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(verbose_name='Номер замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_paid',
            field=models.IntegerField(verbose_name='Оплачена сума'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 24, 1, 655220), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 24, 1, 655220), verbose_name='Дата почтаку'),
        ),
    ]
