# Generated by Django 4.2.3 on 2023-10-22 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0019_alter_order_code_alter_order_sum_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=326)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='paytype',
            field=models.CharField(max_length=255, null=True, verbose_name='Метод оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_commission',
            field=models.CharField(max_length=255, null=True, verbose_name='Liqpay комісія'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_card_mask_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер карти платника'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус оплати'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 16, 14, 15, 735401), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 16, 14, 15, 735401), verbose_name='Дата почтаку'),
        ),
    ]
