# Generated by Django 4.2.3 on 2023-10-22 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0020_orderstatus_order_paytype_order_receiver_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статусы', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(max_length=326, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 16, 33, 28, 834254), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 16, 33, 28, 834254), verbose_name='Дата почтаку'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
