# Generated by Django 4.2.3 on 2023-10-22 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0021_remove_orderitem_order_alter_orderstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сума')),
                ('sum_paid', models.IntegerField(verbose_name='Оплачена сума')),
                ('code', models.CharField(verbose_name='Номер замовлення')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('paytype', models.CharField(max_length=255, null=True, verbose_name='Метод оплати')),
                ('sender_card_mask_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер карти платника')),
                ('receiver_commission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Liqpay комісія')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travel_api.orderstatus')),
            ],
            options={
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 16, 34, 1, 616012), verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 16, 34, 1, 616012), verbose_name='Дата почтаку'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number', models.IntegerField(verbose_name='Номер місця')),
                ('name', models.CharField(verbose_name='Імʼя')),
                ('surname', models.CharField(verbose_name='Фамілія')),
                ('phone', models.CharField(verbose_name='Номер телефону')),
                ('sum', models.IntegerField(verbose_name='Сума')),
                ('is_primary_contact', models.BooleanField(verbose_name='Контакт для звʼязку')),
                ('verification_code', models.IntegerField(verbose_name='Код верифікації')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_api.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name_plural': 'Пасажири замовлення',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='travel_api.tour'),
        ),
    ]
