# Generated by Django 4.2.3 on 2023-10-28 13:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_api", "0025_tourprogram_order_alter_additionaloption_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaloption",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Назва",
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="free_places",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Кількість вільних місць",
            ),
        ),
    ]
