# Generated by Django 4.2.3 on 2023-10-31 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_api", "0026_tourprogram_order_alter_additionaloption_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourprogram",
            name="image_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="tourprogram",
            name="is_landmark",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tour",
            name="date_end",
            field=models.DateField(verbose_name="Дата кінця"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="date_start",
            field=models.DateField(verbose_name="Дата початку"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="places",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Кількість місць",
            ),
        ),
    ]
