# Generated by Django 4.2.3 on 2023-11-02 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "travel_api",
            "0028_tour_description_ru_tour_description_uk_tour_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="name_ru",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Назва опції",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="name_uk",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Назва опції",
            ),
        ),
    ]
