# Generated by Django 4.2.3 on 2023-11-02 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_api", "0029_option_name_ru_option_name_uk_option_tour_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionaloption",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="additionaloption",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="additionaloption",
            name="name_ru",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Назва",
            ),
        ),
        migrations.AddField(
            model_name="additionaloption",
            name="name_uk",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Назва",
            ),
        ),
    ]
