# Generated by Django 4.2.3 on 2023-11-06 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travel_api", "0033_season_name_ru_season_name_uk_tourprogram_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderstatus",
            options={
                "verbose_name": "Статуси",
                "verbose_name_plural": "Статуси замовлень",
            },
        ),
        migrations.AlterField(
            model_name="tourprogram",
            name="image_url",
            field=models.URLField(null=True, verbose_name="Зображення"),
        ),
        migrations.AlterField(
            model_name="tourprogram",
            name="is_landmark",
            field=models.BooleanField(default=False, verbose_name="Визначне місце?"),
        ),
        migrations.AlterField(
            model_name="tourprogram",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="program",
                to="travel_api.tour",
                verbose_name="Тур",
            ),
        ),
        migrations.AlterField(
            model_name="tourprogram",
            name="tour_days",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="travel_api.tourday",
                verbose_name="День програми",
            ),
        ),
        migrations.AlterField(
            model_name="tourprogram",
            name="tour_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="travel_api.tourdayoption",
                verbose_name="Опція",
            ),
        ),
    ]
