# Generated by Django 4.2.3 on 2023-11-28 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_api", "0034_alter_orderstatus_options_tourprogram_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="options/"),
        ),
    ]
