# Generated by Django 4.2.3 on 2023-11-28 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_api", "0035_tourprogram_order_alter_option_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaloption",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="additional_options/",
                verbose_name="Іконка",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="aws_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="tours/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="options/", verbose_name="Іконка"
            ),
        ),
        migrations.AlterField(
            model_name="tourday",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="tour_day/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="tourdayoption",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tour_day_options/",
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="tourprogram",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tour_program/",
                verbose_name="Зображення",
            ),
        ),
    ]
