# Generated by Django 4.2.3 on 2024-02-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_api", "0037_tourprogram_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourdayoption",
            name="date_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата кінця"
            ),
        ),
        migrations.AlterField(
            model_name="tourdayoption",
            name="date_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата початку"
            ),
        ),
    ]
